spring.application.name=Inventory-Management-System

spring.docker.compose.enabled=false
#spring.docker.compose.file=compose.yml
#
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://frodo:5432/ims-db
spring.datasource.url=jdbc:postgresql://ims-db.c4r8amqe400z.us-east-1.rds.amazonaws.com:5432/ims_db?sslmode=require
spring.datasource.username=${RDS_USERNAME:postgres}
spring.datasource.password=${RDS_PASSWORD:Urz8zL5205oFoyR!}
#
## This line will cause our app to automatically set up, and even update the database schema to match the JPA entities we?ll create for our project
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
## JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#
## Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# LOCAL HOST

#spring.application.name=Inventory-Management-System

#spring.docker.compose.enabled=false
#spring.docker.compose.file=compose.yml
#spring.mvc.hiddenmethod.filter.enabled=true

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://frodo:5432/ims-db
#spring.datasource.username=${LOCAL_DB_USER}
#spring.datasource.password=${SECRET_KEY}

# This line will cause our app to automatically set up, and even update the database schema to match the JPA entities we?ll create for our project
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG

logging.level.root=INFO
logging.level.com.crus.cart_microservice=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.data=DEBUG
logging.level.org.springframework.transaction=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#spring.security.oauth2.client.registration.google.client-id=479096137676-pfrn22stian49fh9341jikuscn5algin.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

#spring.security.oauth2.client.registration.github.client-id=Ov23liYvOy2rAn7f5x2p
#spring.security.oauth2.client.registration.github.client-secret=94d5554556bf313ebb079726ec601e201fa1e385

logging.level.org.springframework.security.oauth2=TRACE